name: Validate Nuget Package
description: Validates that the contents of a '.nupkg' and '.snupkg' are as expected

inputs:
  artifact-path:
    description: The location of the artifacts directory
    required: true

runs:
  using: composite
  
  steps:
    - id: validate
      shell: bash
      run: |
        shopt -s globstar
        
        for snupkg in ${{ inputs.artifact-path }}/**/*.snupkg; do
          if [[ -f "$snupkg" ]]; then
            echo "Testing SourceLink in: $snupkg"
            TEMP_DIR=$(mktemp -d)
            unzip -q "$snupkg" -d "$TEMP_DIR"
        
            for pdb in "$TEMP_DIR"/**/*.pdb; do
              if [[ -f "$pdb" ]]; then
                dotnet sourcelink test "$pdb"
              fi
            done
        
            rm -rf "$TEMP_DIR"
          fi
        done
        
        echo "Checking for analyzers in NuGet package..."
        ANALYZER_FOUND=false
        
        for nupkg in ${{ inputs.artifact-path }}/**/*.nupkg; do
          if [[ -f "$nupkg" ]]; then
            echo "Checking package: $nupkg"
            TEMP_DIR=$(mktemp -d)
            unzip -q "$nupkg" -d "$TEMP_DIR"
            
            if [[ -d "$TEMP_DIR/analyzers/dotnet/cs" ]]; then
              DLL_COUNT=$(find "$TEMP_DIR/analyzers/dotnet/cs" -name "*.dll" | wc -l)
              if [[ $DLL_COUNT -gt 0 ]]; then
                echo "Found $DLL_COUNT analyzer DLL(s) in $nupkg"
                ls -la "$TEMP_DIR/analyzers/dotnet/cs/"*.dll
                ANALYZER_FOUND=true
              else
                echo "Analyzer directory exists but contains no DLLs"
              fi
            else
              echo "No analyzer directory found at analyzers/dotnet/cs"
            fi
            
            rm -rf "$TEMP_DIR"
          fi
        done
        
        if [[ "$ANALYZER_FOUND" != "true" ]]; then
          echo "::error::No analyzers found in NuGet package; expected FunctionJunction.Generator.dll in analyzers/dotnet/cs/"
          exit 1
        fi