name: Publish Nuget Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Extract and Validate Version
      id: extract_version
      run: |
        VERSION=${GITHUB_REF_NAME#v}

        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc|preview)(\.[0-9]+)?)?$ ]]; then
          echo "::error ::Invalid version format: $VERSION"
          exit 1
        fi

        echo "::notice ::Package version extracted: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Build
      run: dotnet build --configuration Release -p:PackageVersion=${{ steps.extract_version.outputs.VERSION }}

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish
      run: dotnet nuget push "artifacts/package/Release/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
