name: Publish NuGet Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag to republish (e.g. v0.0.1-alpha or v1.0.0)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'release' && github.event.release.tag_name) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '')

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - id: extract-version
      uses: ./.github/extract-version
      with:
        tag-name: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.tag }}

    - id: build
      uses: ./.github/build
      with:
        package-version: ${{ steps.extract-version.outputs.version }}

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - uses: ./.github/validate-nupkg
      with:
        artifact-path: ${{ steps.build.outputs.artifact-path }}

    - name: Publish
      run: >-
        dotnet nuget push "${{ steps.build.outputs.artifact }}/**/*.nupkg"
        --api-key "${{ secrets.NUGET_API_KEY }}"
        --source "https://api.nuget.org/v3/index.json"
        --skip-duplicate
